# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tsfeatures',
                'doc_host': 'https://jope35.github.io',
                'git_url': 'https://github.com/jope35/tsfeatures',
                'lib_path': 'tsfeatures'},
  'syms': {'tsfeatures.core': {'tsfeatures.core.foo': ('core.html#foo', 'tsfeatures/core.py')}}}
